import kotlin.String

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Update this file with
 *   `$ ./gradlew buildSrcVersions`
 */
object Libs {
  /**
   * http://tools.android.com
   */
  const val constraint_layout: String = "com.android.support.constraint:constraint-layout:" +
      Versions.constraint_layout

  /**
   * https://developer.android.com/testing
   */
  const val espresso_core: String = "com.android.support.test.espresso:espresso-core:" +
      Versions.espresso_core

  /**
   * http://developer.android.com/tools/extras/support-library.html
   */
  const val appcompat_v7: String = "com.android.support:appcompat-v7:" + Versions.appcompat_v7

  /**
   * https://developer.android.com/studio
   */
  const val com_android_tools_build_gradle: String = "com.android.tools.build:gradle:" +
      Versions.com_android_tools_build_gradle

  /**
   * https://developer.android.com/studio
   */
  const val lint_gradle: String = "com.android.tools.lint:lint-gradle:" + Versions.lint_gradle

  const val mpandroidchart: String = "com.github.PhilJay:MPAndroidChart:" + Versions.mpandroidchart

  /**
   * http://github.com/vanniktech/gradle-maven-publish-plugin/
   */
  const val gradle_maven_publish_plugin: String = "com.vanniktech:gradle-maven-publish-plugin:" +
      Versions.gradle_maven_publish_plugin

  const val de_fayard_buildsrcversions_gradle_plugin: String =
      "de.fayard.buildSrcVersions:de.fayard.buildSrcVersions.gradle.plugin:" +
      Versions.de_fayard_buildsrcversions_gradle_plugin

  /**
   * http://junit.org
   */
  const val junit: String = "junit:junit:" + Versions.junit
}
